# action.yml
# https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: 'octorules-sync'
description: 'Run doctena-org/octorules to deploy your Cloudflare Rules config.'
inputs:
  config_path:
    description: 'Path, relative to your repository root, of the config file
                  you would like octorules to use.'
    required: true
    default: 'config.yaml'
  doit:
    description: 'Really do it? Set "--doit" to apply changes; Any other
                  string to only plan.'
    required: false
    default: ''
  force:
    description: 'Run octorules sync with --force to bypass safety thresholds?'
    required: false
    default: 'No'
  checksum:
    description: 'Pass a plan checksum to octorules sync for drift protection.
                  Only used when doit is "--doit".'
    required: false
    default: ''
  phases:
    description: 'Space separated list of rule phases to sync (e.g.
                  "cache_rules redirect_rules"). Leave empty for all phases.'
    required: false
    default: ''
  zones:
    description: 'Space separated list of zones to sync, leave empty to sync
                  all zones in the config file.'
    required: false
    default: ''
  add_pr_comment:
    description: 'Add plan as a comment, when triggered by a pull request?'
    required: true
    default: 'No'
  pr_comment_token:
    description: 'Provide a token to use, if you set add_pr_comment to Yes.'
    required: true
    default: 'Not set'
outputs:
  log:
    description: '`octorules` command output'
    value: ${{ steps.run.outputs.log }}
  plan:
    description: 'Planned changes from octorules'
    value: ${{ steps.run.outputs.plan }}
  exit_code:
    description: 'The exit code from octorules. For plan: 0 = no changes,
                  2 = changes detected, 1 = error. For sync: 0 = success,
                  1 = error.'
    value: ${{ steps.run.outputs.exit_code }}
  checksum:
    description: 'SHA-256 plan checksum for drift protection (plan mode only).'
    value: ${{ steps.run.outputs.checksum }}

runs:
  using: 'composite'
  steps:
    - name: Run octorules
      id: run
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
        DOIT: ${{ inputs.doit }}
        FORCE: ${{ inputs.force }}
        CHECKSUM: ${{ inputs.checksum }}
        PHASES: ${{ inputs.phases }}
        ZONES: ${{ inputs.zones }}
      run: ${GITHUB_ACTION_PATH}/scripts/run.sh
      shell: bash
      working-directory: ${{ github.workspace }}
    - name: Add pull request comment
      id: comment
      env:
        ADD_PR_COMMENT: ${{ inputs.add_pr_comment }}
        PR_COMMENT_TOKEN: ${{ inputs.pr_comment_token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: ${GITHUB_ACTION_PATH}/scripts/comment.sh
      shell: bash
      working-directory: ${{ github.workspace }}
branding:
  icon: 'shield'
  color: 'orange'
