#!/bin/bash
# Add or update a pull request comment with the octorules plan.

# Requires these, provided in action.yml:
# - ADD_PR_COMMENT (skip unless "Yes")
# - PR_COMMENT_TOKEN (fail if empty)
# - PR_NUMBER (skip if empty — not a PR event)
# - GITHUB_REPOSITORY (owner/repo)

set -euo pipefail
# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

: "${GITHUB_WORKSPACE:?GITHUB_WORKSPACE is not set}"

_planfile="${GITHUB_WORKSPACE}/octorules-sync.plan"
# Prefer the HTML plan file for PR comments (renders tables).
_htmlfile="${GITHUB_WORKSPACE}/octorules-plan.html"
if [ -s "${_htmlfile}" ]; then
  _planfile="${_htmlfile}"
fi
_marker="<!-- octorules-sync-plan -->"

if [ "${ADD_PR_COMMENT}" != "Yes" ]; then
  echo "SKIP: \$ADD_PR_COMMENT is not 'Yes'."
  exit 0
fi

if [ -z "${PR_COMMENT_TOKEN}" ] || [ "${PR_COMMENT_TOKEN}" = "Not set" ]; then
  echo "FAIL: \$PR_COMMENT_TOKEN is not set."
  exit 1
fi

if [ -z "${PR_NUMBER}" ]; then
  echo "SKIP: \$PR_NUMBER is not set."
  echo "Was this workflow run triggered from a pull request?"
  exit 0
fi

if ! [[ "${PR_NUMBER}" =~ ^[0-9]+$ ]]; then
  echo "FAIL: \$PR_NUMBER must be numeric (got '${PR_NUMBER}')"
  exit 1
fi

# Safe for ephemeral GitHub Actions runners — token is destroyed after the job.
export GH_TOKEN="${PR_COMMENT_TOKEN}"

echo "INFO: \$ADD_PR_COMMENT is 'Yes' and \$PR_COMMENT_TOKEN is set."

# Construct the comment body with a hidden marker for deduplication.
_lint_resultfile="${GITHUB_WORKSPACE}/octorules-sync.lint"
_audit_resultfile="${GITHUB_WORKSPACE}/octorules-sync.audit"
_sha="$(git log -1 --format='%h' 2>/dev/null)" || _sha="unknown"

# Append a result section to the comment body.
# Usage: _append_section "Title" "resultfile" "EXIT_CODE_VAR" "clean message"
_append_section() {
  local _title="$1"
  local _file="$2"
  local _exit_var="$3"
  local _clean_msg="$4"
  local _exit_code="${!_exit_var:-}"

  if [ -s "${_file}" ]; then
    _body+="
### ${_title}

\`\`\`
$(cat "${_file}")
\`\`\`

---
"
  elif [ "${_exit_code}" = "0" ]; then
    _body+="
### ${_title}

${_clean_msg}

---
"
  fi
}

_body="${_marker}
## Octorules Plan for ${_sha}
"

_append_section "Audit Results" "${_audit_resultfile}" "AUDIT_EXIT_CODE" "Audit: clean, no findings."
_append_section "Lint Results" "${_lint_resultfile}" "LINT_EXIT_CODE" "Lint: clean, no issues found."

_body+="
### Rule Changes

"

if [ -s "${_planfile}" ]; then
  _body+="$(cat "${_planfile}")"
elif [ -f "${_planfile}" ]; then
  _body+="_No changes detected._"
else
  _body+="_No plan output (run step was skipped)._"
fi

_body+="

---
*Automatically generated by [octorules-sync](https://github.com/doctena-org/octorules-sync)*"

# Look for an existing comment with our marker.
# Note: If multiple jobs update the same PR concurrently, the last one wins.
# Use workflow 'concurrency' groups to prevent this.
_existing_comment_id=""
if ! _existing_comment_id="$(
  retry 3 2 gh api \
    --paginate \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    --jq '.[] | select(.body | startswith("<!-- octorules-sync-plan -->")) | .id' \
  | head -n 1
)"; then
  echo "WARN: Could not fetch existing comments after 3 attempts. A new comment will be created."
  _existing_comment_id=""
fi

if [ -n "${_existing_comment_id}" ]; then
  echo "INFO: Updating existing comment ${_existing_comment_id}."
  retry 3 2 gh api \
    --method PATCH \
    "repos/${GITHUB_REPOSITORY}/issues/comments/${_existing_comment_id}" \
    -f body="${_body}" > /dev/null || {
    echo "FAIL: Could not update PR comment after 3 attempts."
    exit 1
  }
else
  echo "INFO: Creating new PR comment."
  retry 3 2 gh api \
    --method POST \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    -f body="${_body}" > /dev/null || {
    echo "FAIL: Could not create PR comment after 3 attempts."
    exit 1
  }
fi
