#!/bin/bash
# Add or update a pull request comment with the octorules plan.

# Requires these, provided in action.yml:
# - ADD_PR_COMMENT (skip unless "Yes")
# - PR_COMMENT_TOKEN (fail if empty)
# - PR_NUMBER (skip if empty — not a PR event)
# - GITHUB_REPOSITORY (owner/repo)

set -o pipefail

_planfile="${GITHUB_WORKSPACE}/octorules-sync.plan"
_marker="<!-- octorules-sync-plan -->"

if [ "${ADD_PR_COMMENT}" != "Yes" ]; then
  echo "SKIP: \$ADD_PR_COMMENT is not 'Yes'."
  exit 0
fi

if [ -z "${PR_COMMENT_TOKEN}" ] || [ "${PR_COMMENT_TOKEN}" = "Not set" ]; then
  echo "FAIL: \$PR_COMMENT_TOKEN is not set."
  exit 1
fi

if [ -z "${PR_NUMBER}" ]; then
  echo "SKIP: \$PR_NUMBER is not set."
  echo "Was this workflow run triggered from a pull request?"
  exit 0
fi

echo "INFO: \$ADD_PR_COMMENT is 'Yes' and \$PR_COMMENT_TOKEN is set."

# Construct the comment body with a hidden marker for deduplication.
_sha="$(git log -1 --format='%h')"
_body="${_marker}
## Octorules Plan for ${_sha}

$(cat "${_planfile}")

---
*Automatically generated by [octorules-sync](https://github.com/doctena-org/octorules-sync)*"

# Look for an existing comment with our marker.
_existing_comment_id=""
_existing_comment_id="$(
  GH_TOKEN="${PR_COMMENT_TOKEN}" gh api \
    --paginate \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    --jq ".[] | select(.body | startswith(\"${_marker}\")) | .id" \
  | head -n 1
)" || true

if [ -n "${_existing_comment_id}" ]; then
  echo "INFO: Updating existing comment ${_existing_comment_id}."
  GH_TOKEN="${PR_COMMENT_TOKEN}" gh api \
    --method PATCH \
    "repos/${GITHUB_REPOSITORY}/issues/comments/${_existing_comment_id}" \
    -f body="${_body}" > /dev/null || {
    echo "FAIL: Could not update PR comment."
    exit 1
  }
else
  echo "INFO: Creating new PR comment."
  GH_TOKEN="${PR_COMMENT_TOKEN}" gh api \
    --method POST \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    -f body="${_body}" > /dev/null || {
    echo "FAIL: Could not create PR comment."
    exit 1
  }
fi
